baseURL = 'https://snowtenshi.github.io/study-hall/'
languageCode = 'pt-br'
title = 'Study Hall'
theme='archie'

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

pagination.pagerSize=4

[params]
	mode="auto" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Um blog pessoal com meus textos da faculdade. Blog construído com Hugo e [tema desenvolvido por Athul](https://github.com/athul/archie)"


[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/snowtenshi"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/gabi-mariano/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4